default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: pwealth_development

test:
  <<: *default
  database: pwealth_test

staging:
  <<: *default
  database: pwealth_staging

production:
  <<: *default
  database: pwealth_production
